files: |
    (?x)^(
        src/.*/.*py
        | tests/.*/.*py
    )$

exclude: |
    (?x)^(
        src/future/.* |
        others/.* |
        examples/.*
    )$


repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        exluce: ^docs/
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check src/
        language: system
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]

  - repo: https://github.com/numpy/numpydoc
    rev: v1.9.0
    hooks:
      - id: numpydoc-validation
        files: ^src/(?!.*tests).+$
