[project]
name = "pyfield"
version = "0.0.1"
description = "Python package for acoustic simulations using the SIR approach."
readme = "README.md"
authors = [
    { name = "Deyver Esteban Rivera", email = "113285895+EstebanRivera08@users.noreply.github.com" }
]
requires-python = ">=3.11,<3.13"
classifiers = [
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
dependencies = [
    "brainglobe-atlasapi>=2.2.1",
    "brainglobe-space>=1.0.3",
    "h5py>=3.13.0",
    "imageio>=2.37.3",
    "imageio-ffmpeg>=0.6.0",
    "matplotlib>=3.10.1",
    "numba>=0.65.0",
    "numpy>= 2.1.2",
    "pyqt5-qt5 >= 5.15.2",
    "pyvista[jupyter]>=0.45.0",
    "scipy>=1.15.2",
]

[tool.ruff]
exclude = []

[project.scripts]
pyfield = "pyfield:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
default = false

[dependency-groups]
dev = [
    "zensical>=0.0.28",
    "ipykernel>=6.29.5",
    "ipympl>=0.9.7",
    "ipython>=9.1.0",
    "ipyvtklink>=0.2.3",
    "ruff>=0.12.0",
    "torch>=2.6.0",
    "pytest>=8.4.2",
    "pytest-cov>=6.0.0",
    "ty>=0.0.10",
    "pytest-pyvista>=0.3.2",
    "mkdocstrings[python]>=1.0.3",
    "prek>=0.2.0",
    "vtk>=9.2.2",
    "pytest-mpl>=0.16.0",
    "tqdm<=4.66.5",
    "codespell>=2.3.0",
    "numpydoc>=1.9.0",
    "pandas>=2.2.3",
    "openpyxl>=3.1.5",
]

[tool.uv.sources]
torch = {index = "pytorch"}

# --------------------------------------------------------------------------- #
#  pytest
# --------------------------------------------------------------------------- #
[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--showlocals",
]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore:The active matplotlib backend.*is non-interactive:UserWarning",
    "ignore:FigureCanvasAgg is non-interactive:UserWarning",
]

# --------------------------------------------------------------------------- #
#  coverage
# --------------------------------------------------------------------------- #
[tool.coverage.run]
source = ["pyfield"]
omit = ["*/examples/*"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:"]

# --------------------------------------------------------------------------- #
#  codespell
# --------------------------------------------------------------------------- #
[tool.codespell]
skip = "*.ipynb,*.lock,examples/*,.git"
ignore-words-list = "ser,hsi,nd,mear,apod,fo,te,bu"

# --------------------------------------------------------------------------- #
# numpydoc
# --------------------------------------------------------------------------- #

[tool.numpydoc_validation]
exclude = [
    '\.__init__$',
    '\._.*$',

    '^\.examples/.*',

]
checks = [
    "all",  # Report on all checks, except the below
    "GL01",
    "ES01",
    "SA01",
    "EX01",
]
numpydoc_validation_checks = ["all", "GL01", "ES01", "SA01", "EX01"]

